var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__90c0bf5a._.js")
R.c("server/chunks/ssr/Desktop_Projects_Megaai_frontend_cc82d0bc._.js")
R.c("server/chunks/ssr/be213_next_dist_esm_build_templates_app-page_7072d2b6.js")
R.c("server/chunks/ssr/[root-of-the-server]__c3438d11._.js")
R.c("server/chunks/ssr/be213_82269418._.js")
R.c("server/chunks/ssr/be213_next_dist_b42b7a1e._.js")
R.c("server/chunks/ssr/Desktop_Projects_Megaai_frontend_src_app_3d05a6bc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__217f7af2._.js")
R.c("server/chunks/ssr/Desktop_Projects_Megaai_frontend_src_app_error_tsx_6b606ec3._.js")
R.c("server/chunks/ssr/Desktop_Projects_Megaai_frontend_src_app_loading_tsx_ee16590a._.js")
R.c("server/chunks/ssr/Desktop_Projects_Megaai_frontend_src_app_not-found_tsx_180370bb._.js")
R.c("server/chunks/ssr/be213_next_dist_client_components_fe63313a._.js")
R.c("server/chunks/ssr/7e03e_Megaai_frontend__next-internal_server_app__not-found_page_actions_da6b2eba.js")
R.m(88418)
module.exports=R.m(88418).exports
